version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: tasklib
      POSTGRES_PASSWORD: tasklib_pass
      POSTGRES_DB: tasklib
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tasklib"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
