site_name: TaskLib
site_description: Simple, durable task queue for PostgreSQL
site_author: TaskLib Contributors
site_url: https://tasklib.example.com

docs_dir: .

theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: blue
  features:
    - content.code.copy
    - content.code.select
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.highlight

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - tables
  - toc:
      title: "On this page"

nav:
  - Home: index.md
  - Getting Started:
      - Installation: getting-started/installation.md
      - Quick Start: getting-started/quick-start.md
      - Your First Task: getting-started/first-task.md
  - Guides:
      - Task Definition: guides/task-definition.md
      - Running Workers: guides/workers.md
      - Error Handling: guides/error-handling.md
  - API Reference:
      - Core: api/core.md
      - Configuration: api/configuration.md
      - Worker: api/worker.md

copyright: Copyright &copy; 2025 TaskLib Contributors. All rights reserved. Licensed under MIT.
