services:
  postgres:
    image: postgres:15-alpine
    container_name: tasklib-postgres-dashboard
    environment:
      POSTGRES_DB: tasklib
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: tasklib-dashboard-api
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/tasklib
    ports:
      - "8989:8989"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
